### PR TITLE
Update links to `<map>` and `<layer>` element definitions

### PR DESCRIPTION
**Pull request by Malvoz**
Update links to `<map>` and `<layer>` element definitions to accommodate for [the merging](https://github.com/Maps4HTML/MapML/pull/78) of the Map Element Proposal into the MapML spec.

### CODE REVIEW

**Comment by Malvoz** [comment]
@prushforth I believe the text still applies to the element definitions in the MapML spec, so I don't think there should be anything blocking us from merging this change. Shall we?

**Comment by prushforth** [comment]
@malvoz Yes please. Note that I'm on holiday ATM so not fully engaged until next week. Thanks.

**Comment by prushforth** [comment]
@Malvoz go ahead and merge when appropriate. I didn't want to merge these commits out of order, if it matters.

**Comment by Malvoz** [comment]
@prushforth I don't have write access to this repo. 😋

**Comment by prushforth** [comment]
Added you as collaborator...

**Pull request closed without merging**
